[project]
name = "denev6-github-io"
version = "0.1.0"
description = "Palette: Personal Blog"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.2.3",
    "langchain-core>=1.2.7",
    "langchain-openai>=1.1.7",
    "pillow>=12.1.0",
]
